server:
  port: 8080

spring:
  application:
    name: scrapper
  liquibase:
    enabled: true
    change-log: file:../migrations/changelog-master.xml
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  access-type: ORM
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.stackexchange.com/2.3
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.github.com
  bot:
    url: http://localhost:8080
  scheduler:
    interval: 60000
    batch-size: 100
    thread-count: 4
  kafka:
    topic:
      name: link-updates
      partitions: 3
      replicas: 3
      min-insync-replicas: 2
      retention-ms: 604800000
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}
  outbox:
    interval: 2000
    max-attempts: 5
clients:
  bot:
    base-url: http://localhost:8080
    connect-timeout: 5s
    read-timeout: 5s
  scrapper:
    base-url: http://localhost:8081
    connect-timeout: 5s
    read-timeout: 5s
