server:
  port: 8080

spring:
  application:
    name: scrapper
  liquibase:
    enabled: true
    change-log: file:migrations/changelog-master.xml
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  access-type: ORM
