server:
  port: 8080

spring:
  application:
    name: bot
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: bot
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: file:../migrations/changelog-master.xml
    enabled: true
  kafka:
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${app.kafka.schema-registry-url}
app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false
  kafka:
    topic:
      name: link-updates
      partitions: 3
      group-id: bot-group
    retry:
      max-attempts: 3
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}

clients:
  bot:
    base-url: http://localhost:8080
    connect-timeout: 5s
    read-timeout: 5s
  scrapper:
    base-url: http://localhost:8081
    connect-timeout: 5s
    read-timeout: 5s
